### PR TITLE
Correct path for oci_home_to_grails.svg

### LINKED ISSUE #25: Broken Link At The Bottom Of Plugin Pages
The bottom of each plugin page includes a broken image link:

Screen Shot 2021-01-21 at 3 09 51 PM

The link is pointing to https://plugins.grails.org/plugin/grails/assets/oci_home_to_grails.svg.

### PR DESCRIPTION
**Pull request by puneetbehl**
Update oci_home_to_grails.svg image path from root instead of relative

### CODE REVIEW

File: src/main/groovy/org/grails/pages/Page.groovy [hunk 1]
```diff
@@ -182,7 +182,7 @@ abstract class Page implements HtmlPage {
                 div(class: 'ocihometograils') {
                     span 'Sponsored by'
                     a(href: "https://objectcomputing.com/products/grails/") {
-                        img(src: 'assets/oci_home_to_grails.svg', alt: 'Object Computing - Home to Grails', width: '300px')
+                        img(src: '/assets/oci_home_to_grails.svg', alt: 'Object Computing - Home to Grails', width: '300px')
```
Comment (jeffscottbrown) [inline src/main/groovy/org/grails/pages/Page.groovy:185]: @puneetbehl Is this going to generate a link to https://objectcomputing.com/products/grails/assets/oci_home_to_grails.svg?

Comment (JasonTypesCodes) [reply src/main/groovy/org/grails/pages/Page.groovy:185]: @jeffbrown It will display the image from: https://plugins.grails.org/assets/oci_home_to_grails.svg

Comment (jeffscottbrown) [reply src/main/groovy/org/grails/pages/Page.groovy:185]: Roger that.  Thanks.  If `https://objectcomputing.com/products/grails/` above were changed to `https://objectcomputing.com/something/else/` would the same thing happen?  I am trying to understand the significance of the trailing `/product/grails/` in the `href`.  Thanks again!

Comment (jeffscottbrown) [reply src/main/groovy/org/grails/pages/Page.groovy:185]: Nevermind... the href is for the anchor, not the image.  My mistake.  Thanks!
